### ISSUE TITLE
Uncaught Error: Cannot find module "./laravel-mentions"

### ISSUE THREAD

**Issue by getwes** [jameslkingsley/laravel-mentions#10]
Hi, 

please can you assist, after reaching this point in your install & setup guide:
<pre>
import Mentions from './laravel-mentions';
window.Mentions = Mentions;
</pre>

I get the following error:
<code>Uncaught Error: Cannot find module "./laravel-mentions"</code>

Please can you assist me in sorting this error out. 
Thanks!

**Comment by jameslkingsley** [comment]
Does `laravel-mentions.js` exist in the same directory as the file that's importing it?

**Comment by getwes** [comment]
Ah! Thanks. Issue has been sorted now.
