### ISSUE TITLE
[Error: ./resources/assets/js/laravel-mentions.js Module build failed

### ISSUE THREAD

**Issue by gaurav16694** [jameslkingsley/laravel-mentions#11]
please look into this issue

**Comment by jameslkingsley** [comment]
Can you show the code you used to include the file in your app?

**Comment by gaurav16694** [comment]
i have use like this in app.js

import Mentions from './laravel-mentions';
window.Mentions = Mentions;
laravel - elixer not able to compile this ES 6 code 
thats why it is throwing build error 
aftr doing some research i found out the for loop can not be compiled in laravel elixer

**Comment by gaurav16694** [comment]
is there any alternative i  can compile this through gulp i am using laravel 5.4

**Comment by jameslkingsley** [comment]
I'll see what I can do today to fix the script so that it compiles. I just compile it using what comes out of Laravel, just `npm run dev`

**Comment by gaurav16694** [comment]
i am getting this error while running npm run dev

ERROR in ./resources/assets/js/laravel-mentions.js
Module build failed: Error
    at ForOfStatement.initialise (/home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:2004:65)
    at /home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:9381:56
    at Array.forEach (native)
    at BlockStatement.initialise (/home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:9381:15)
    at FunctionExpression.initialise (/home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:858:12)
    at FunctionExpression.initialise (/home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:2098:31)
    at Node.initialise (/home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:858:12)
    at /home/sach/funngageupdated/node_modules/buble/dist/buble.umd.js:856:61
    at Array.forEach (native)
 @ ./resources/assets/js/app.js 36:0-42

**Comment by gaurav16694** [comment]
but when i convert the code to ES 5 it work fine..

**Comment by jameslkingsley** [comment]
Yeah it's that for-of statement. I'll just change it to a simple for loop and it should work.

**Comment by gaurav16694** [comment]
yeah that will work...and after that i am stuck in the view where the json data  is coming from backend on keyup but i cant see any drop box to select the response

**Comment by jameslkingsley** [comment]
Which browser are you using btw?

**Comment by gaurav16694** [comment]
I am using Chrome and Firefox both having the same issue

**Comment by jameslkingsley** [comment]
Can you try compiling again using the latest commit? (afaik you just set the composer version to `dev-master` and then re-publish the assets to get the updated script).

**Comment by jameslkingsley** [comment]
Is this still an open issue?

**Comment by gaurav16694** [comment]
It is now getting build successfully but I am getting error in calling the
mention api

**Comment by jameslkingsley** [comment]
Are you assigning it to the `window` like:
```js
import Mentions from './laravel-mentions';
window.Mentions = Mentions;
```

and including the compiled `app.js` in your layout?

**Comment by gaurav16694** [comment]
Yes the same way

**Comment by jameslkingsley** [comment]
That's odd, maybe try clearing your browser cache? I'm not sure why else it wouldn't be defined.
