### ISSUE TITLE
error when using use HasMentions in model

### ISSUE THREAD

**Issue by gaurav16694** [jameslkingsley/laravel-mentions#12]
i am getting error when i use use

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

use Kingsley\Mentions\Traits\HasMentions;

class Comment extends Model
{

    use HasMentions;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

`
this error i am getting 

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`funngage`.`comments`, CONSTRAINT `comments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)) (SQL: insert into `comments` (`updated_at`, `created_at`) values (2017-11-08 18:01:08, 2017-11-08 18:01:08))

**Comment by gaurav16694** [comment]
i am also getting thiss error

(1/1) BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::mention()

when i am using 
$comment->mention($request->mentions);
in my controller

**Comment by jameslkingsley** [comment]
For multiple traits you need to do `use HasMentions, SoftDeletes;`

**Comment by jameslkingsley** [comment]
Also I don't think the foreign key error is related to mentions.

**Comment by gaurav16694** [comment]
if i remove  use HasMentions;
my code run smoothly

**Comment by jameslkingsley** [comment]
Can you post the full file?

**Comment by gaurav16694** [comment]
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

use Kingsley\Mentions\Traits\HasMentions;


class Comment extends Model
{

    use HasMentions, SoftDeletes;

    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'post_id',
        'moment_files_id',
        'comment',
        'is_page_comment',
    ];

    public $with = ['user'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function getHashIdAttribute()
    {
        return md5($this->id . $this->user->id);
    }

    /*
    public function replies()
    {
        return $this->hasMany(Post::class, 'post_id')->orderBy('created_at', "asc");
    }*/

    public function getIfiLikedAttribute()
    {
        if(isset(Auth::user()->id)){
            return $this->likes->where('user_id', '=', Auth::user()->id)->count() ? 'liked' : "like";
        }else{
            return '';
        }
    }
    public function getIfiLikedApiAttribute()
    {
        if(isset(Auth::user()->id)){
            return $this->likes->where('user_id', '=', Auth::user()->id)->count() ? '1' : "0";
        }else{
            return '';
        }
    }

    public function moment_files()
    {
        return $this->hasMany(MomentFiles::class)->orderBy('created_at', 'DESC');
    }

    public function likes()
    {
        return $this->morphMany(Like::class, 'likeable');
    }
    
    public function getUsersListAttribute()
    {
        if ($this->likes->count() == 0)
            return 'No Likes yet!';

        $list = [];
        $list[] = '<ul class="like-users-list">';
        foreach ($this->likes as $like) {
            $list[] = '<li>' . $like->user->getName() . '</li>';
        }
        $list[] = '</ul>';
        $likes = implode('', $list);

        return $likes;

    }

   
}
`

**Comment by gaurav16694** [comment]
and my controller code 
            $comment = Comment::create([
                'post_id' => $postId,
                'user_id' => Auth::id(),
                'comment' => $reply,
                'is_page_comment'=>'2',
            ]);
            $comment->mention($request->mentions);

**Comment by jameslkingsley** [comment]
And you're still getting `Call to undefined method Illuminate\Database\Query\Builder::mention()` or just the foreign key error?

**Comment by gaurav16694** [comment]
this error come when i remove the use HasMentions;
my comment cretaed successfully but 
but if i use use HasMentions;
comment didnt get saved in db and i got foreign key error

**Comment by gaurav16694** [comment]
i got this working when i used like this in my controller

            $comment = new Comment;
            $comment->post_id=$postId;
            $comment->user_id=Auth::id();
            $comment->comment= $reply;
            $comment->is_page_comment='2';
             $comment->save();
            $comment->mention($request->mentions);

**Comment by jameslkingsley** [comment]
Ok I know the issue, I'll put out a fix soon.

**Comment by jameslkingsley** [comment]
Fixed in 33fe08eb4f446766bc564617c375476a6dda0be9. Make sure you're using `dev-master` in your composer file and run `composer update`. That will fix the `Comment::create( ... )`.
