### ISSUE TITLE
How we add filters in User Model

### ISSUE THREAD

**Issue by gaurav16694** [jameslkingsley/laravel-mentions#13]

**Comment by gaurav16694** [comment]
or can we have multilple models ?

**Comment by jameslkingsley** [comment]
I'm not exactly sure what you mean. You have "pools" of models that can be mentioned, the default set of pools being just `App\User`. Do you mean you want to add your own query filters to `App\User`?

**Comment by gaurav16694** [comment]
Now the result is coming from all the row of user table but I want the
result from a filtered user list.

**Comment by jameslkingsley** [comment]
I just added the ability to apply filters. See https://github.com/jameslkingsley/laravel-mentions#filters

**Comment by gaurav16694** [comment]
thank you i will look into it..
can we make the mentions as a link  ?

**Comment by gaurav16694** [comment]
do i need  to update the package or it will work without updating.
because its not working

**Comment by jameslkingsley** [comment]
You need to update.

**Comment by gaurav16694** [comment]
i am getting this error on updating package
 jameslkingsley/laravel-mentions 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement 
do i need to update the php or is there any workaround ?

**Comment by gaurav16694** [comment]
hello  can we add more columns in the json coming from backend ?

**Comment by jameslkingsley** [comment]
Moved to #16.

**Comment by jameslkingsley** [comment]
@gaurav16694 Take a look at https://github.com/jameslkingsley/laravel-mentions#resources for customising the JSON response.
