### ISSUE TITLE
mention data is now coming when using multiple instances on single page.

### ISSUE THREAD

**Issue by gaurav16694** [jameslkingsley/laravel-mentions#14]
Please look into the issue 
when i use multiple instances like in post comments. with including also the editable part `<input type="hidden" name="mentions" id="mentions" value="{{ $comment->mentions()->encoded() }}">`

upto a single comment it works fine but when i try mention in next comment in the same page mentions user id doesn't show up

**Comment by gaurav16694** [comment]
may be the error is coming because of mutiple `<input type="hidden" name="mentions" id="mentions" value="{{ $comment->mentions()->encoded() `}}">` instances on one page

**Comment by gaurav16694** [comment]
i tried to figure out a solution i.e i am dynamically initializing mention when i open the edit box like this
`new Mentions({
    input: '.has-mentions'+id,
    output: '#comment_mention' + id,
    pools: [{ trigger: '@',pool: 'users',display: 'fname',reference: 'id'
    }]`

but it is giving me this errror
Uncaught Error: [Tribute] Must pass in a DOM node or NodeList.
    at Tribute.attach (eval at <anonymous> (app.js?1510212428:116), <anonymous>:157:23)
    at Mentions.attach (eval at <anonymous> (app.js?1510212428:103), <anonymous>:97:26)
    at new Mentions (eval at <anonymous> (app.js?1510212428:103), <anonymous>:17:24)
    at editComment (wall.js?1510221527:453)
    at HTMLAnchorElement.onclick (timeline:1)

**Comment by gaurav16694** [comment]
hii FYI i have solved this problem but now i get stuck at the point where if i add new mention or remove mention from editable comment the mentions user data is not updating.
adding and removing mention in new comment works fine but i am not able to figure out why this doesn't work in case of editing comments

**Comment by jameslkingsley** [comment]
Both the input and output parameters need to be unique. Creating new comments and editing existing ones work for me by doing the following:

```js
new Mentions({
    input: '.has-mentions',
    output: '#mentions',
    pools: [{
        trigger: '@',
        pool: 'users',
        display: 'name',
        reference: 'id'
    }]
});

new Mentions({
    input: '.has-mentions-update',
    output: '#mentions_update',
    pools: [{
        trigger: '@',
        pool: 'users',
        display: 'name',
        reference: 'id'
    }]
});
```

**Comment by gaurav16694** [comment]
thanks i didn't longer a issue i am having some issue in my js.
But now i got another issue like when i edit the comment the how to handle the db entry..because there is no any function for removing the unmentioned entry and update the entry for new mentioned comment

**Comment by jameslkingsley** [comment]
Moved to #17.
