### ISSUE TITLE
- jameslkingsley/laravel-mentions 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.

### ISSUE THREAD

**Issue by gaurav16694** [jameslkingsley/laravel-mentions#15]

**Comment by jameslkingsley** [comment]
This package requires PHP version 7.1. I don't have any plans to support older versions, sorry.

**Comment by gaurav16694** [comment]
i have updated my php version but now i am getting another error 
jameslkingsley/laravel-mentions 1.2.0 requires illuminate/database ^5.5
i am using laravel 5.4
i do not wanna update to 5.5. is there any other way around ?

**Comment by jameslkingsley** [comment]
Unfortunately not as it uses [API Resources](https://laravel.com/docs/5.5/eloquent-resources) that were introduced in 5.5.
