### ISSUE TITLE
Extend the model

### ISSUE THREAD

**Issue by fernandocoronatomf** [jameslkingsley/laravel-mentions#18]
I have multiple connections and I need to customise my Mention model.
Can you provide a way to do that?

**Comment by jameslkingsley** [comment]
Is it not possible with the [service container](https://laravel.com/docs/master/container)?

**Comment by fernandocoronatomf** [comment]
Using the extend() method? Would that work? I am new to laravel

**Comment by jameslkingsley** [comment]
In your app's service provider you can try using the following in the register method:

```php
$this->app->bind('Kingsley\Mentions\Models\Mention', function ($app) {
    $mention = new Kingsley\Mentions\Models\Mention();

    // Modify the $mention model here

    return $mention;
});
```
