### ISSUE TITLE
Editing Config file

### ISSUE THREAD

**Issue by mmutas** [jameslkingsley/laravel-mentions#19]
When I change the config file config/mentions.php, it does not change anything. BUT when i change the mentions.php file in vendor/.. directory, the changes are applied. Am I missing something?

**Comment by mmutas** [comment]
Or when i change the MentionServiceProvider.php line from
$this->mergeConfigFrom(__DIR__.'/../config/mentions.php', 'mentions');

to 
$this->mergeConfigFrom(__DIR__.'/../../../../config/mentions.php', 'mentions');
 
this also works. But changes in the vendor directory does not make any sens as you know. I am a little bit stucked right now.

**Comment by mmutas** [comment]
Our users table has firstname and lastname fields rather than name so i tried to write DB::raw("CONCAT(firstname,' ',lastname)") to column field of mentions.php. This messed up the cache of the configurations and i fixed this by deleting manually the config cache. 

But I still couldn't find a way to search as full name. I can't pass an argument to filter I guess so.. Do you have any advice for this?

**Comment by jameslkingsley** [comment]
It's currently not possible to change that.
