### ISSUE TITLE
Tribute must pass in DOM node or NodeList

### ISSUE THREAD

**Issue by henryonsoftware** [jameslkingsley/laravel-mentions#21]
I do all things the same in the readme.md but got this error `Uncaught Error: [Tribute] Must pass in a DOM node or NodeList.` Can anyone fix it?

**Comment by jameslkingsley** [comment]
Hey thanks for the issue report, unfortunately, I don't have the time to adequately maintain this package. I'd recommend [Xetaravel-Mentions](https://github.com/XetaIO/Xetaravel-Mentions) which appears to be better maintained with similar functionality.

In hindsight, this package has tried to do too much to implement this feature. I think if you're looking to implement mentions, you'd be better off implementing the front-end manually, and abstracting the back-end to that package above or writing your own API.

Hope this helps!
