### ISSUE TITLE
Any chance for update to latest Laravel 6?

### ISSUE THREAD

**Issue by Luppakorva** [jameslkingsley/laravel-mentions#39]
Would really appreciate it, using this at he moment but sadly have to drop it as I can't use it in 6.10 (or 6.2, those are the ones I tested) at all.

**Comment by jameslkingsley** [comment]
Hey thanks for the issue report, unfortunately, I don't have the time to adequately maintain this package. I'd recommend [Xetaravel-Mentions](https://github.com/XetaIO/Xetaravel-Mentions) which appears to be better maintained with similar functionality. Alternatively, you could fork this repo and bump the versions to use in Laravel 6.

In hindsight, this package has tried to do too much to implement this feature. I think if you're looking to implement mentions, you'd be better off implementing the front-end manually, and abstracting the back-end to that package above or writing your own API.

Hope this helps!
