### ISSUE TITLE
After cloning the example I tried to run composer install but it is displaying the following errors. 

### ISSUE THREAD

**Issue by yestif** [jameslkingsley/laravel-mentions#40]
In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mentions.users' doesn't exist (SQL: select * from `users`)  

In Connection.php line 326:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mentions.users' doesn't exist  

And my other question is that does it work on the latest laravel versions?

**Comment by jameslkingsley** [comment]
Hey, that error is to do with the `users` table is missing - probably a misconfiguration in the example.

I haven't tested this package with the latest Laravel versions, though on first thought I can't see why it wouldn't be compatible.

Unfortunately, I don't have the time to adequately maintain this package. I'd recommend [Xetaravel-Mentions](https://github.com/XetaIO/Xetaravel-Mentions) which appears to be better maintained with similar functionality.

In hindsight, this package has tried to do too much to implement this feature. I think if you're looking to implement mentions, you'd be better off implementing the front-end manually, and abstracting the back-end to that package above or writing your own API.

Hope this helps!

**Comment by yestif** [comment]
Hey James,
Thank you for getting back to me. But it is displaying the error before even letting me migrate the database.
