### ISSUE TITLE
Names not appearing after following instructions

### ISSUE THREAD

**Issue by gregvarghese** [jameslkingsley/laravel-mentions#6]
Hi @jameslkingsley !

I'm trying to use your library but can't seem to get it to work. I created a sample laravel project and followed your instructions but the names don't appear for me. I can't figure out what I'm doing wrong. 

I've attached the sample project so you can see what I've done. You may need to run npm install and composer update as the zip file became over 40 megs otherwise. I have it set to generate 50 test users using php artisan db:seed. The mentions url seems to return the user list, but I'm not seeing the list in the textarea to select from.

Do you have any ideas on what I could be missing or overlooking? 

Thanks in advance!

[mention-test-example.zip](https://github.com/jameslkingsley/laravel-mentions/files/1099356/mention-test-example.zip)

**Comment by jameslkingsley** [comment]
It all looks like it's setup correctly, however it doesn't seem like the `app.js` is being loaded properly. The URL for it is correct, but none of the dependencies are available such as `window.Vue`.

**Comment by gregvarghese** [comment]
Hi James,

Thanks for the quick reply! 

I checked and had to run npm run dev to get window.Vue and the tributejs files to load after running npm install and composer update. 

Please forgive my ignorance as I'm still trying to figure out how the package works, but how do you log mentions directly from the dev tools console? I tried modifying the code to var mentions = new Mentions({... and the console.log(mentions); but nothing shows up. 

Best regards,
Greg

**Comment by jameslkingsley** [comment]
Sorry, what I meant by logging mentions in dev tools, was that if everything loaded correctly you should be able to do `console.log(Mentions)` and see the `Mentions` class, rather than an undefined error. If the class is still undefined then either none of the JS is being loaded or just the Mentions isn't being included in the build somehow.

**Comment by gregvarghese** [comment]
Hi James, 

Thanks for clarifying. I couldn't get it to work with the previous project I attached, so I created a brand new one which appears to be somewhat working. I'm getting the dropdown, but it's empty, and I can't figure out why. I tested the api/mentions URL (using Insomonia) and passed in a JSON string with {"p": "users"}, and it successfully returns the user list in JSON, but the mentions list isn't showing them. The console.log(Mentions) and Vue.js appear to be working correctly in this one but the list is empty, so I think I may just be overlooking something but can't figure out what. 

I added the entire project to the zip but it's too large to attach to the GitHub item since it's 40 MB, so I uploaded it to dropbox: https://www.dropbox.com/s/b5hhc51ibumoypl/mentions.zip?dl=0

If we can get the sample project working, I'd be happy to contribute it to your project for anyone else who wants to use it for reference. 

Thanks!

**Comment by jameslkingsley** [comment]
I downloaded the dropbox zip and ran it and it worked as expected for me (after changing the DB environment vars). Are you getting any errors?

![Gif](https://i.gyazo.com/acb9a1f1a674aba1d1dda231af3745f7.gif)

**Comment by gregvarghese** [comment]
On a whim, I tried the code on a different machine and it's working for me now. The other laptop doesn't work and I have absolutely no idea why. 😢 

Thanks for responding so quickly. I sincerely appreciate the help and time. Hopefully you can use the zip project as an example. 😄

**Comment by jameslkingsley** [comment]
Happy to help, glad it's working!

**Comment by gaurav16694** [comment]
hey i am facing the same issue here the drop box is empty but the ajax call is returning data from backend

**Comment by jameslkingsley** [comment]
I think this could be related to some unsupported code in the script that some browsers don't like. I'll look into it today.

**Comment by gaurav16694** [comment]
please provide a sample project it will be really helpfull

**Comment by jameslkingsley** [comment]
Here's an example project: https://github.com/jameslkingsley/laravel-mentions/tree/master/example

**Comment by gaurav16694** [comment]
thanks it solved my problem..
Can you help me implement  mention in the text-area instead of content-editable when i use text-area the output comes like

helllo <span class="mention-node" data-object="users:564">@Morgan Knapp</span>   

  and how can i apply the filter in the user model.

**Comment by jameslkingsley** [comment]
You can't use text areas directly as they don't render HTML.
