### ISSUE TITLE
is there a chance installing this package on php 5.6 ?

### ISSUE THREAD

**Issue by rrasyidilib** [jameslkingsley/laravel-mentions#7]
iam using php 5.6+ and this package build on php 7, I tried to install this package using composer --ignore-platform-reqs but it doesn't work, is there another way to install this package without changing my php version ?

thanks.

**Comment by jameslkingsley** [comment]
It's possible to run on 5.6 with some changes. I'll see what I can do tomorrow.

**Comment by rrasyidilib** [comment]
awesome.

thanks for your response, I really appreciate it, this package is really helpful.

Thanks.
